// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig =  {
    "aws_appsync_graphqlEndpoint": "https://ns5at7hrkjbgta6mmqz2aommx4.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cwil5kzlrnc77d2tbbqmhfjm5m",
};

export default awsconfig;